services:
  - type: web
    name: mumbai-swap-backend
    env: node
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://mumbai-swap.vercel.app
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /api/auth/status 